// web/src/lib/player/IrisChrome.svelte
<script lang="ts" module>
	export type ChromePip = { supported: boolean; active: boolean; toggle: () => Promise<void> };
	export type NextEpisode = { label: string; onPlay: () => void };
	/** How long the controls stay after the last movement while playing. */
	export const HIDE_AFTER_MS = 2500;
</script>

<script lang="ts">
	// The player's controls over the stage: a top bar (the page's own snippet), the timeline,
	// one row of 44 px buttons, the audio/subtitles panel and the shortcuts list. Engine-agnostic:
	// it only sees the EngineHandle and the MediaState its events keep current.
	//
	// The controls hide after a still moment while playing, never while paused, scrubbing, a panel
	// is open, or a control holds the keyboard focus (WCAG 2.4.7, 2.2.1): a key or a movement
	// brings them back, and so does the focus arriving on one of them.
	import type { Snippet } from 'svelte';
	import { untrack } from 'svelte';
	import type { EngineHandle } from '@iris/core/engine';
	import type { Manifest, SubtitleTrack } from '@iris/core/manifest-client';
	import { clock } from '@iris/api/format';
	import Icon, { type IconName } from '#lib/components/Icon.svelte';
	import Range from '#lib/components/Range.svelte';
	import type { MediaState } from './media-state.svelte.ts';
	import ScrubBar from './ScrubBar.svelte';
	import TrackPanel from './TrackPanel.svelte';
	import { actionFor, nextSpeed, ownedByControl, shortcutList, type PlayerAction } from './shortcuts.ts';
	import { volumeText } from './spoken.ts';
	import { toggleFullscreen } from './browser.ts';

	interface Props {
		handle: EngineHandle | null;
		media: MediaState;
		manifest: Manifest;
		/** An endless stream: no timeline, no skips, a « Live » label. */
		live?: boolean;
		activeSubtitle: SubtitleTrack | null;
		onSubtitleChange: (track: SubtitleTrack | null) => void;
		/** Index into `manifest.audio`. */
		activeAudioIndex: number;
		onAudioPick: (id: string) => void;
		/** The stage: full screen target, where the keys are listened to. */
		fullscreenTarget: HTMLElement | null;
		pip: ChromePip;
		nextEpisode?: NextEpisode | null;
		/** Facts for the playback details, before what the engine reports. */
		debugInfo?: [string, string][];
		onVisibleChange?: (visible: boolean) => void;
		onVolumeChange?: (volume: number, muted: boolean) => void;
		/** The top bar's content (the way back, the title, the facts line). */
		top?: Snippet;
		/** Where an audio/subtitle choice is kept, said in the panel. */
		keptFor?: string;
		/** Said politely to screen readers (a speed change). */
		onsay?: (text: string) => void;
	}
	let {
		handle,
		media,
		manifest,
		live = false,
		activeSubtitle,
		onSubtitleChange,
		activeAudioIndex,
		onAudioPick,
		fullscreenTarget,
		pip,
		nextEpisode = null,
		debugInfo = [],
		onVisibleChange,
		onVolumeChange,
		top,
		keptFor,
		onsay
	}: Props = $props();

	type Panel = 'none' | 'tracks' | 'shortcuts';
	let panel = $state<Panel>('none');
	let details = $state(false);
	let scrubTo = $state<number | null>(null);
	let recent = $state(true);
	let controlFocused = $state(false);
	let fullscreen = $state(false);
	let tracksButton = $state<HTMLButtonElement | null>(null);
	let shortcutsButton = $state<HTMLButtonElement | null>(null);

	const shownTime = $derived(scrubTo ?? media.time);
	const remaining = $derived(media.duration !== null ? Math.max(0, media.duration - shownTime) : null);
	const blocked = $derived(media.paused || panel !== 'none' || scrubTo !== null || controlFocused);
	const visible = $derived(recent || blocked);
	const hasTracks = $derived(manifest.subtitles.length > 0 || manifest.audio.length > 1);
	const canSpeed = $derived(!live && !!handle?.videoElement());

	$effect(() => onVisibleChange?.(visible));

	// approved web timer: the controls' auto-hide after HIDE_AFTER_MS of stillness while playing
	// (CLAUDE.md rule 2; never while `blocked`: see `visible`)
	let hideTimer: ReturnType<typeof setTimeout> | undefined;
	function wake() {
		recent = true;
		clearTimeout(hideTimer);
		hideTimer = setTimeout(() => (recent = false), HIDE_AFTER_MS);
	}
	$effect(() => () => clearTimeout(hideTimer));
	// a blocker lifted (a panel closed, playback resumed): a fresh still moment before hiding
	$effect(() => {
		if (!blocked) untrack(wake);
	});

	function refresh() {
		media.read(handle);
	}

	function togglePlay() {
		if (!handle) return;
		if (handle.paused()) void handle.play().catch(() => undefined);
		else handle.pause();
		refresh();
	}
	function seekTo(s: number) {
		if (!handle) return;
		handle.seek(Math.max(0, s));
		refresh();
	}
	function seekBy(d: number) {
		if (!handle || live) return;
		seekTo(handle.currentTime() + d);
	}
	function setVolume(v: number) {
		if (!handle) return;
		const next = Math.max(0, Math.min(1, v));
		handle.setVolume(next);
		if (next > 0 && handle.muted()) handle.setMuted(false);
		refresh();
		onVolumeChange?.(handle.volume(), handle.muted());
	}
	function toggleMute() {
		if (!handle) return;
		handle.setMuted(!handle.muted());
		refresh();
		onVolumeChange?.(handle.volume(), handle.muted());
	}
	function changeSpeed(step: 1 | -1) {
		const v = handle?.videoElement();
		if (!v || live) return;
		v.playbackRate = nextSpeed(v.playbackRate, step);
		refresh();
		onsay?.(v.playbackRate === 1 ? 'Normal speed' : `Speed ${v.playbackRate}×`);
	}
	function fs() {
		void toggleFullscreen(fullscreenTarget);
	}
	function openPanel(p: Panel) {
		panel = panel === p ? 'none' : p;
		if (panel === 'none') (p === 'tracks' ? tracksButton : shortcutsButton)?.focus();
	}
	function closePanel() {
		const was = panel;
		panel = 'none';
		(was === 'tracks' ? tracksButton : shortcutsButton)?.focus();
	}

	function run(a: PlayerAction) {
		switch (a.kind) {
			case 'toggle-play':
				return togglePlay();
			case 'seek-by':
				return seekBy(a.seconds);
			case 'seek-to-fraction':
				if (handle && media.duration) seekTo(media.duration * a.fraction);
				return;
			case 'volume-by':
				return handle && setVolume(handle.volume() + a.delta);
			case 'toggle-mute':
				return toggleMute();
			case 'fullscreen':
				return fs();
			case 'tracks':
				return hasTracks && openPanel('tracks');
			case 'pip':
				return pip.supported && void pip.toggle();
			case 'shortcuts':
				return openPanel('shortcuts');
			case 'speed-by':
				return changeSpeed(a.step);
			case 'escape':
				if (panel !== 'none') closePanel();
				return;
		}
	}

	// the keys, on the stage (so they act wherever the focus is inside the player)
	$effect(() => {
		const el = fullscreenTarget;
		if (!el || !handle) return;
		const onKey = (e: KeyboardEvent) => {
			wake();
			if (ownedByControl(e.target, e.key)) return;
			const a = actionFor(e, live);
			if (!a) return;
			// Escape with nothing open is the browser's (it leaves full screen)
			if (a.kind === 'escape' && panel === 'none') return;
			e.preventDefault();
			run(a);
		};
		if (el.tabIndex < 0) el.tabIndex = 0;
		el.addEventListener('keydown', onKey);
		return () => el.removeEventListener('keydown', onKey);
	});

	// the pointer, on the whole stage (the controls layer lets it through to the picture)
	$effect(() => {
		const el = fullscreenTarget;
		if (!el) return;
		const onDown = (e: PointerEvent) => {
			outside(e);
			// a touch has no hover: a tap on hidden controls only brings them back (the stage's
			// click that follows does not also toggle playback)
			if (e.pointerType === 'touch' && !visible) el.dataset.pressConsumed = '';
			wake();
		};
		// a lifted finger leaves too (touch pointers end in pointerleave): only a mouse leaving
		// the stage hides the controls at once
		const onLeave = (e: PointerEvent) => {
			if (media.paused || e.pointerType === 'touch') return;
			clearTimeout(hideTimer);
			recent = false;
		};
		el.addEventListener('pointermove', wake);
		el.addEventListener('pointerdown', onDown);
		el.addEventListener('pointerleave', onLeave);
		return () => {
			el.removeEventListener('pointermove', wake);
			el.removeEventListener('pointerdown', onDown);
			el.removeEventListener('pointerleave', onLeave);
		};
	});

	// full screen state, for the button's words
	$effect(() => {
		const el = fullscreenTarget;
		if (!el) return;
		const doc = el.ownerDocument;
		const on = () => (fullscreen = doc.fullscreenElement === el);
		on();
		doc.addEventListener('fullscreenchange', on);
		return () => doc.removeEventListener('fullscreenchange', on);
	});

	// a pointer press outside an open panel closes it, and only that: the stage's click that
	// follows does not also toggle playback (`data-press-consumed`, read by PlayerStage)
	function outside(e: PointerEvent) {
		const el = fullscreenTarget;
		if (el) delete el.dataset.pressConsumed;
		if (panel === 'none') return;
		const t = e.target as Element | null;
		if (t?.closest('.stage-panel, [data-panel-trigger]')) return;
		panel = 'none';
		if (el) el.dataset.pressConsumed = '';
	}

	const stats = $derived.by(() => {
		if (!details || !handle) return [] as [string, string][];
		// refreshed with the playhead's events while open
		void media.time;
		void media.paused;
		void media.buffered;
		return handle.stats?.() ?? [];
	});

	interface Btn {
		label: string;
		key: string;
		icon: IconName;
		onclick: () => void;
		pressed?: boolean;
	}
	const playBtn = $derived<Btn>({
		label: media.paused ? 'Play' : 'Pause',
		key: 'Space',
		icon: media.paused ? 'play' : 'pause',
		onclick: togglePlay
	});
</script>

{#snippet button(b: Btn, extra?: { ref?: (el: HTMLButtonElement) => void; expanded?: boolean; trigger?: boolean; wide?: boolean })}
	<button
		type="button"
		class={['ctl', extra?.wide && 'wide-only']}
		aria-label="{b.label}, {b.key}"
		aria-keyshortcuts={b.key === 'Space' ? 'Space k' : b.key}
		aria-pressed={b.pressed}
		aria-expanded={extra?.expanded}
		aria-haspopup={extra?.expanded === undefined ? undefined : 'dialog'}
		data-panel-trigger={extra?.trigger ? '' : undefined}
		{@attach (el: HTMLButtonElement) => extra?.ref?.(el)}
		onclick={b.onclick}
	>
		<Icon name={b.icon} size={22} />
		<span class="tip" aria-hidden="true">{b.label} <kbd>{b.key}</kbd></span>
	</button>
{/snippet}

{#if handle}
	<div
		class="chrome"
		class:shown={visible}
		role="presentation"
		onfocusin={(e) => {
			wake();
			const t = e.target as Element;
			controlFocused = t.matches(':focus-visible') && !!t.closest('button, a[href], input, [role="slider"]');
		}}
		onfocusout={(e) => {
			if (!(e.relatedTarget instanceof Element) || !e.currentTarget.contains(e.relatedTarget)) controlFocused = false;
		}}
	>
		<div class="top" data-iris-chrome>
			{@render top?.()}
		</div>

		<div class="middle">
			{#if details}
				<dl class="details" data-iris-chrome aria-label="Playback details">
					{#each [...debugInfo, ...stats] as [k, v], i (i)}
						<div>
							<dt>{k}</dt>
							<dd>{v}</dd>
						</div>
					{/each}
				</dl>
			{/if}
			{#if panel === 'tracks'}
				<TrackPanel
					audio={manifest.audio}
					activeAudio={activeAudioIndex}
					subtitles={manifest.subtitles}
					activeSubtitle={activeSubtitle?.stream_idx ?? null}
					onaudio={(i) => onAudioPick(String(i))}
					onsubtitle={onSubtitleChange}
					{keptFor}
					onclose={closePanel}
				/>
			{:else if panel === 'shortcuts'}
				<div
					class="stage-panel"
					role="dialog"
					aria-labelledby="shortcuts-title"
					tabindex="-1"
					data-iris-chrome
					{@attach (el) => el.focus()}
					onkeydown={(e) => {
						if (e.key === 'Escape') {
							e.stopPropagation();
							closePanel();
						}
					}}
				>
					<div class="panel-head">
						<h2 id="shortcuts-title" class="panel-title">Keyboard shortcuts</h2>
						<button class="ctl" type="button" aria-label="Close" onclick={closePanel}><Icon name="x" /></button>
					</div>
					<dl class="keys">
						{#each shortcutList(live) as s (s.does)}
							<div>
								<dt>
									{#each s.keys as k (k)}<kbd>{k}</kbd>{/each}
								</dt>
								<dd>{s.does}</dd>
							</div>
						{/each}
					</dl>
					<button class="text-btn" type="button" aria-pressed={details} onclick={() => (details = !details)}>
						{details ? 'Hide playback details' : 'Show playback details'}
					</button>
				</div>
			{/if}
		</div>

		<div class="bottom" data-iris-chrome>
			{#if live}
				<div class="row live-row">
					<span class="live"><span class="dot" aria-hidden="true"></span>Live</span>
				</div>
			{:else}
				<div class="row scrub-row">
					<span class="time" aria-hidden="true">{clock(shownTime)}</span>
					<ScrubBar
						duration={media.duration}
						current={shownTime}
						buffered={media.buffered}
						chapters={manifest.chapters}
						onscrub={(s) => (scrubTo = s)}
						onseek={(s) => {
							scrubTo = null;
							seekTo(s);
						}}
						oncancel={() => (scrubTo = null)}
					/>
					<span class="time" aria-hidden="true">{remaining !== null ? `−${clock(remaining)}` : '--:--'}</span>
				</div>
			{/if}
			<div class="row controls">
				{@render button(playBtn)}
				{#if !live}
					{@render button({ label: 'Back 10 seconds', key: 'J', icon: 'rotate-ccw', onclick: () => seekBy(-10) })}
					{@render button({ label: 'Forward 10 seconds', key: 'L', icon: 'rotate-cw', onclick: () => seekBy(10) })}
				{/if}
				<div class="volume">
					{@render button({
						label: media.muted ? 'Unmute' : 'Mute',
						key: 'M',
						icon: media.muted || media.volume === 0 ? 'volume-x' : 'volume-2',
						onclick: toggleMute
					})}
					<div class="volume-range">
						<Range
							label="Volume"
							hideLabel
							value={media.muted ? 0 : Math.round(media.volume * 100)}
							step={5}
							valueText={(v) => volumeText(v / 100, media.muted && v === 0)}
							live
							send={async (v) => setVolume(v / 100)}
						/>
					</div>
				</div>
				<span class="spacer"></span>
				{#if canSpeed && media.rate !== 1}<span class="fact">{media.rate}×</span>{/if}
				{#if nextEpisode && !live}
					<button type="button" class="text-btn next" aria-label={nextEpisode.label} onclick={nextEpisode.onPlay}>
						<Icon name="skip-forward" /><span class="next-label">{nextEpisode.label}</span>
					</button>
				{/if}
				{#if hasTracks}
					{@render button(
						{ label: 'Audio and subtitles', key: 'C', icon: 'captions', onclick: () => openPanel('tracks'), pressed: undefined },
						{ ref: (el) => (tracksButton = el), expanded: panel === 'tracks', trigger: true }
					)}
				{/if}
				{#if pip.supported}
					{@render button(
						{
							label: pip.active ? 'Leave picture in picture' : 'Picture in picture',
							key: 'P',
							icon: 'picture-in-picture',
							onclick: () => void pip.toggle(),
							pressed: pip.active
						},
						{ wide: !pip.active }
					)}
				{/if}
				{@render button({
					label: fullscreen ? 'Leave full screen' : 'Full screen',
					key: 'F',
					icon: fullscreen ? 'minimize' : 'maximize',
					onclick: fs
				})}
				{@render button(
					{ label: 'Keyboard shortcuts', key: '?', icon: 'info', onclick: () => openPanel('shortcuts') },
					{ ref: (el) => (shortcutsButton = el), expanded: panel === 'shortcuts', trigger: true, wide: true }
				)}
			</div>
		</div>
	</div>
{/if}

<style>
	/* the controls layer: clicks on its empty middle reach the stage (play/pause, full screen) */
	.chrome {
		position: absolute;
		inset: 0;
		z-index: 10;
		display: flex;
		flex-direction: column;
		justify-content: space-between;
		color: var(--stage-ink);
		pointer-events: none;
	}
	.top,
	.bottom {
		pointer-events: auto;
		background: var(--stage-scrim);
		opacity: 0;
		transition: opacity 0.2s ease;
	}
	.chrome.shown .top,
	.chrome.shown .bottom {
		opacity: 1;
	}
	/* hidden, a control is still reached by Tab: arriving there shows the bar (onfocusin) */
	.chrome:not(.shown) .top,
	.chrome:not(.shown) .bottom {
		pointer-events: none;
	}
	.top {
		padding: var(--s-2) var(--s-3);
	}
	.top:empty {
		display: none;
	}
	.middle {
		position: relative;
		flex: 1;
		min-height: 0;
		display: flex;
		align-items: flex-end;
		justify-content: flex-end;
		padding: var(--s-2);
		gap: var(--s-2);
	}
	.bottom {
		display: grid;
		gap: var(--s-1);
		padding: var(--s-1) var(--s-3) var(--s-2);
	}
	.row {
		display: flex;
		align-items: center;
		gap: var(--s-1);
		min-width: 0;
	}
	.scrub-row {
		gap: var(--s-3);
	}
	.time {
		font: var(--t-meta);
		font-variant-numeric: tabular-nums;
		color: var(--stage-ink);
		flex: none;
	}
	.controls {
		flex-wrap: wrap;
	}
	.spacer {
		flex: 1;
	}
	.ctl {
		position: relative;
		display: grid;
		place-items: center;
		width: var(--control-h);
		height: var(--control-h);
		border: 0;
		border-radius: var(--radius);
		background: transparent;
		color: var(--stage-ink);
		cursor: pointer;
		flex: none;
	}
	.ctl:hover,
	.ctl[aria-pressed='true'],
	.ctl[aria-expanded='true'] {
		background: var(--stage-line);
	}
	.tip {
		position: absolute;
		bottom: calc(100% + var(--s-1));
		left: 50%;
		transform: translateX(-50%);
		display: none;
		gap: var(--s-1);
		align-items: center;
		padding: var(--s-1) var(--s-2);
		border-radius: var(--radius);
		background: var(--stage-raised);
		color: var(--stage-ink);
		font: var(--t-meta);
		white-space: nowrap;
		pointer-events: none;
	}
	.ctl:hover .tip,
	.ctl:focus-visible .tip {
		display: inline-flex;
	}
	.tip kbd,
	.keys kbd {
		background: var(--stage);
		color: var(--stage-muted);
		border-color: var(--stage-line);
	}
	.volume {
		display: flex;
		align-items: center;
	}
	.volume-range {
		width: 6.5rem;
	}
	/* a phone: the volume is the device's keys, the next episode an icon (its name stays its
	   label), the shortcuts list (no keyboard) and picture in picture leave the row; the panels become a sheet over the
	   page, the stage being too short to hold them */
	@media (max-width: 599px) {
		.volume-range,
		.wide-only,
		.next-label {
			display: none;
		}
		.text-btn.next {
			padding: 0;
			width: var(--control-h);
			justify-content: center;
		}
		.bottom {
			padding-inline: var(--s-1);
		}
		.row {
			gap: 0;
		}
		.scrub-row {
			gap: var(--s-2);
		}
		:global(.stage-panel) {
			position: fixed;
			z-index: 40;
			left: 0;
			right: 0;
			bottom: 0;
			width: 100%;
			max-height: 75dvh;
			border-radius: var(--radius-2xl) var(--radius-2xl) 0 0;
			padding-bottom: calc(var(--s-4) + env(safe-area-inset-bottom, 0px));
		}
	}
	.text-btn {
		display: inline-flex;
		align-items: center;
		gap: var(--s-2);
		min-height: var(--control-h);
		padding: 0 var(--s-3);
		border: 1px solid var(--stage-line);
		border-radius: var(--radius);
		background: transparent;
		color: var(--stage-ink);
		font: var(--t-label);
		cursor: pointer;
		max-width: 100%;
	}
	.text-btn:hover {
		background: var(--stage-line);
	}
	.fact {
		font: var(--t-meta);
		color: var(--stage-muted);
		padding-inline: var(--s-2);
	}
	.live-row {
		min-height: var(--control-h-xs);
	}
	.live {
		display: inline-flex;
		align-items: center;
		gap: var(--s-2);
		font: var(--t-label);
		letter-spacing: 0.06em;
		text-transform: uppercase;
	}
	.dot {
		width: var(--s-2);
		height: var(--s-2);
		border-radius: 50%;
		background: var(--status-down);
	}
	/* panels inside the stage (not portalled: they stay in full screen) */
	:global(.stage-panel) {
		pointer-events: auto;
		display: flex;
		flex-direction: column;
		gap: var(--s-3);
		max-height: 100%;
		width: min(26rem, calc(100% - 2 * var(--s-3)));
		padding: var(--s-4);
		border: 1px solid var(--stage-line);
		border-radius: var(--radius-l);
		background: var(--stage-raised);
		color: var(--stage-ink);
		box-shadow: var(--shadow-pop);
		overflow: auto;
	}
	.panel-head {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}
	.panel-title {
		font: var(--t-group);
	}
	.keys {
		margin: 0;
		display: grid;
		gap: var(--s-2);
	}
	.keys div {
		display: flex;
		gap: var(--s-3);
		align-items: baseline;
	}
	.keys dt {
		display: flex;
		gap: var(--s-1);
		min-width: 6rem;
	}
	.keys dd {
		margin: 0;
		font: var(--t-secondary);
	}
	.details {
		pointer-events: auto;
		position: absolute;
		top: var(--s-2);
		left: var(--s-2);
		max-width: min(28rem, calc(100% - 2 * var(--s-2)));
		max-height: 70%;
		overflow: auto;
		margin: 0;
		padding: var(--s-3);
		border-radius: var(--radius-l);
		background: var(--stage-scrim);
		font: var(--t-tiny);
		font-family: var(--font-mono);
	}
	.details div {
		display: flex;
		gap: var(--s-2);
	}
	.details dt {
		width: 5rem;
		flex: none;
		color: var(--stage-muted);
	}
	.details dd {
		margin: 0;
		min-width: 0;
		overflow-wrap: anywhere;
	}
	@media (prefers-reduced-motion: reduce) {
		.top,
		.bottom {
			transition: none;
		}
	}
</style>

// web/src/lib/iris-core/IrisChrome.tsx
/**
 * Custom player chrome — replaces Vidstack's default layout. Receives
 * an `EngineHandle` from `IrisPlayer` and reads/writes its state to
 * drive a scrub bar + play/pause + volume + fullscreen + unified
 * subtitle/audio pickers.
 *
 * Design rules:
 * - Engine-agnostic: no `<video>`-specific paths here. Tier C/D
 *   (canvas) and Tier A/B/F (`<video>`) flow through the same code.
 * - Polls the handle every animation frame for `currentTime` and
 *   `paused` — engines that don't emit fine-grained events still get
 *   accurate UI updates.
 * - Subtitle picker is *unified*: WebVTT (native `<track>`), ASS
 *   (libass overlay), PGS (libpgs overlay) all appear in one list
 *   labelled with their format.
 */

import { useEffect, useRef, useState } from "react";
import {
  Captions,
  Languages,
  Maximize,
  Pause,
  PictureInPicture2,
  Play,
  Bug,
  Rewind,
  FastForward,
  SkipForward,
  Volume2,
  VolumeX,
} from "lucide-react";

import type { EngineAudioTrack, EngineHandle } from "./engine";
import type { Manifest, SubtitleTrack } from "./manifest-client";
import { subtitleOverlayKind } from "./subs/subtitle-overlay";

export type ChromePipControl = {
  supported: boolean;
  isActive: boolean;
  toggle: () => Promise<void>;
};

export type IrisChromeProps = {
  handle: EngineHandle | null;
  manifest: Manifest;
  /** Live-TV mode: LIVE badge instead of the scrub bar, no ±10 s skips,
   *  no time display, seek keyboard shortcuts disabled. */
  live?: boolean;
  /** Active subtitle track (for both native and overlay paths). null = off. */
  activeSubtitle: SubtitleTrack | null;
  onSubtitleChange: (track: SubtitleTrack | null) => void;
  /** Index into `manifest.audio` of the currently-active track. The
   *  chrome highlights it; user picks call `onAudioPick`. */
  activeAudioIndex: number;
  /** Called when the user picks an audio track from the menu. Bridges
   *  to either `handle.setAudioTrack` (Tier F) or a remount (others). */
  onAudioPick: (id: string) => void;
  /** Container element used as the fullscreen target. */
  fullscreenTarget: HTMLElement | null;
  /** Document PiP controller. `supported=false` hides the button. */
  documentPip: ChromePipControl;
  title: string;
  /** Next-episode control. `null` hides it. Lives in the transport row
   *  rather than floating over the picture, mirroring the TV player: there
   *  the button sits in the native controller layout so the D-pad reaches
   *  it like any other transport control. */
  nextEpisode?: { label: string; onPlay: () => void } | null;
  /** Static facts for the debug panel, prepended to whatever the engine
   *  reports. The panel is hidden entirely when this is absent AND the
   *  handle has no `stats`. */
  debugInfo?: Array<[string, string]>;
  /** Notified whenever the controls visibility flips. The parent
   *  uses this to hide the mouse cursor over the player surface
   *  while playback is uninterrupted — matches the cursor-hide
   *  behaviour every native fullscreen player has. */
  onControlsVisibleChange?: (visible: boolean) => void;
  /** Notified when the user changes volume or mute (slider, mute button, or
   *  keyboard). Lets the parent persist volume device-locally. */
  onVolumeChange?: (volume: number, muted: boolean) => void;
};

export function IrisChrome(props: IrisChromeProps) {
  const { handle, manifest } = props;
  const live = props.live === true;

  // Polled state. We deliberately don't trust engine events for the
  // chrome's display state because engines emit at different cadences;
  // a 60-Hz tick gives us a consistent UI feel.
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState<number | null>(manifest.duration_s ?? null);
  const [paused, setPaused] = useState(true);
  const [volume, setVolume] = useState(1);
  const [muted, setMuted] = useState(false);
  const [buffered, setBuffered] = useState<Array<[number, number]>>([]);
  // Audio tracks come from the manifest (source of truth) — that way
  // even engines whose track-reporting is racey (e.g., hls.js taking
  // a beat to populate `hls.audioTracks` after MANIFEST_PARSED) still
  // show every rendition the user can pick. The chrome marks the
  // active one based on the parent's `activeAudioIndex` state.
  const audioTracks: EngineAudioTrack[] = manifest.audio.map((a, i) => ({
    id: String(i),
    label: a.title ?? a.lang?.toUpperCase() ?? `Audio ${i + 1}`,
    lang: a.lang ?? undefined,
    active: i === props.activeAudioIndex,
  }));
  const [menu, setMenu] = useState<"none" | "subs" | "audio">("none");
  const [debugOpen, setDebugOpen] = useState(false);
  const [engineStats, setEngineStats] = useState<Array<[string, string]>>([]);
  const [scrubbing, setScrubbing] = useState(false);
  // Read inside the rAF loop, which must not restart when the panel opens.
  const debugOpenRef = useRef(false);
  debugOpenRef.current = debugOpen;
  const [hovered, setHovered] = useState(true);
  const scrubTargetRef = useRef<number | null>(null);

  // Auto-hide controls after 2.5s of mouse-still during playback.
  const hideTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const resetHideTimer = () => {
    setHovered(true);
    if (hideTimer.current) clearTimeout(hideTimer.current);
    hideTimer.current = setTimeout(() => {
      if (!paused && !scrubbing && menu === "none") setHovered(false);
    }, 2500);
  };

  // Surface controls-visibility to the parent (IrisPlayer) so it can
  // hide the cursor on the wrapper while playback is uninterrupted.
  // `paused` keeps controls up, same as menus and scrubbing — so the
  // cursor only disappears when the user is actually watching.
  const controlsVisible = hovered || paused || menu !== "none" || scrubbing;
  const onControlsVisibleChange = props.onControlsVisibleChange;
  useEffect(() => {
    onControlsVisibleChange?.(controlsVisible);
  }, [controlsVisible, onControlsVisibleChange]);

  // rAF loop drives the displayed state from the engine.
  useEffect(() => {
    if (!handle) return;
    let rafId = 0;
    const tick = () => {
      if (!scrubbing) setCurrentTime(handle.currentTime());
      setDuration(handle.duration());
      setPaused(handle.paused());
      setVolume(handle.volume());
      setMuted(handle.muted());
      setBuffered(handle.buffered());
      // Only while the panel is open: these reads walk TimeRanges and query
      // playback quality, which is not free at 60 Hz.
      if (debugOpenRef.current) setEngineStats(handle.stats?.() ?? []);
      rafId = requestAnimationFrame(tick);
    };
    rafId = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(rafId);
  }, [handle, scrubbing]);

  // Surface volume / mute changes to the parent so it can persist them
  // device-locally. Driven off the polled state, so it fires once for every
  // change regardless of source (slider, mute button, keyboard).
  const onVolumeChange = props.onVolumeChange;
  const lastVolRef = useRef<{ v: number; m: boolean } | null>(null);
  useEffect(() => {
    if (!onVolumeChange) return;
    const last = lastVolRef.current;
    if (last && (last.v !== volume || last.m !== muted)) {
      onVolumeChange(volume, muted);
    }
    lastVolRef.current = { v: volume, m: muted };
  }, [volume, muted, onVolumeChange]);

  // Keyboard shortcuts on the fullscreen container.
  useEffect(() => {
    if (!handle || !props.fullscreenTarget) return;
    const el = props.fullscreenTarget;
    const onKey = (e: KeyboardEvent) => {
      if (e.target instanceof HTMLInputElement || e.target instanceof HTMLSelectElement) return;
      switch (e.key) {
        case " ":
        case "k":
          e.preventDefault();
          if (handle.paused()) void handle.play();
          else handle.pause();
          break;
        case "ArrowLeft":
        case "j":
          e.preventDefault();
          if (!live) handle.seek(Math.max(0, handle.currentTime() - 10));
          break;
        case "ArrowRight":
        case "l":
          e.preventDefault();
          if (!live) handle.seek(handle.currentTime() + 10);
          break;
        case "f":
          e.preventDefault();
          void toggleFullscreen(props.fullscreenTarget);
          break;
        case "m":
          e.preventDefault();
          handle.setMuted(!handle.muted());
          break;
        case "ArrowUp":
          e.preventDefault();
          handle.setVolume(Math.min(1, handle.volume() + 0.1));
          break;
        case "ArrowDown":
          e.preventDefault();
          handle.setVolume(Math.max(0, handle.volume() - 0.1));
          break;
        default:
          break;
      }
    };
    // Make the container focusable so it actually receives key events.
    if (el.tabIndex < 0) el.tabIndex = 0;
    el.addEventListener("keydown", onKey);
    return () => el.removeEventListener("keydown", onKey);
  }, [handle, props.fullscreenTarget, live]);

  // Click-to-toggle is handled at the wrapper level in `IrisPlayer`
  // — see `onSurfaceClick` there. We used to also register a
  // `flex-1.onClick={...}` here that was supposed to ignore chrome-
  // internal clicks, but the `closest('[data-iris-chrome]')` check
  // matched our own root wrapper (which carries `data-iris-chrome`)
  // and consequently bailed on every click, so it was always dead
  // code. Removed; we let pointer events pass through the
  // transparent surface area to the wrapper instead.

  if (!handle) return null;

  return (
    <div
      onMouseMove={resetHideTimer}
      onMouseLeave={() => {
        if (hideTimer.current) clearTimeout(hideTimer.current);
        if (!paused) setHovered(false);
      }}
      // The chrome root deliberately does NOT carry
      // `data-iris-chrome` — that marker is now on the bottom bar
      // only. Clicks on the chrome's transparent upper area bubble
      // up to `IrisPlayer`'s wrapper-level `onSurfaceClick`
      // (play/pause + dblclick → fullscreen) and our walk-up
      // ignore-check finds no interactive ancestor, so the action
      // fires. Clicks on the bottom bar still bail correctly
      // because the bar's `data-iris-chrome` is hit first.
      className="absolute inset-0 z-10 flex flex-col"
    >
      <div className="pointer-events-none flex-1">
        {debugOpen && (
          <div
            // `data-iris-chrome` so a click here is not treated as a tap on
            // the video surface, which toggles playback. Interactive on
            // purpose: the panel scrolls when a value is long.
            data-iris-chrome
            className="pointer-events-auto absolute left-2 top-2 max-h-[70%] max-w-[min(28rem,calc(100%-1rem))] overflow-auto rounded-lg bg-black/75 p-3 font-mono text-[11px] leading-relaxed text-white/90 backdrop-blur sm:left-3 sm:top-3"
          >
            {[...(props.debugInfo ?? []), ...engineStats].map(([k, v]) => (
              <div key={k} className="flex gap-2">
                <span className="w-20 shrink-0 text-white/50">{k}</span>
                <span className="min-w-0 break-words">{v}</span>
              </div>
            ))}
          </div>
        )}
      </div>

      <div
        data-iris-chrome
        className={`pointer-events-auto flex flex-col gap-1 bg-gradient-to-t from-black/80 to-transparent px-2 pb-2 pt-10 text-white transition-opacity duration-200 sm:px-3 sm:pt-12 ${
          hovered || paused || menu !== "none" ? "opacity-100" : "opacity-0"
        }`}
      >
        {/* Title sits above the controls bar but only while hovered. */}
        <div className="line-clamp-1 text-xs opacity-80">{props.title}</div>

        {/* Scrub bar — a live stream has no timeline to scrub. */}
        {!live && (
          <ScrubBar
            durationSeconds={duration}
            currentSeconds={scrubbing ? (scrubTargetRef.current ?? currentTime) : currentTime}
            bufferedRanges={buffered}
            onScrub={(s) => {
              setScrubbing(true);
              scrubTargetRef.current = s;
              setCurrentTime(s);
            }}
            onScrubEnd={(s) => {
              handle.seek(s);
              scrubTargetRef.current = null;
              setScrubbing(false);
            }}
          />
        )}

        <div className="flex items-center gap-0.5 text-[12px] sm:gap-1">
          <Button
            label={paused ? "Play" : "Pause"}
            icon={paused ? <Play className="size-5" /> : <Pause className="size-5" />}
            onClick={() => (paused ? void handle.play() : handle.pause())}
          />
          {live ? (
            <span className="ml-1 flex select-none items-center gap-1.5 text-[11px] font-semibold uppercase tracking-wider opacity-90">
              <span className="size-2 animate-pulse rounded-full bg-red-500" />
              Live
            </span>
          ) : (
            <>
              <Button
                label="-10s"
                icon={<Rewind className="size-4" />}
                onClick={() => handle.seek(Math.max(0, handle.currentTime() - 10))}
              />
              <Button
                label="+10s"
                icon={<FastForward className="size-4" />}
                onClick={() => handle.seek(handle.currentTime() + 10)}
              />
              {props.nextEpisode && (
                <button
                  title={props.nextEpisode.label}
                  aria-label={props.nextEpisode.label}
                  onClick={props.nextEpisode.onPlay}
                  className="ml-0.5 flex shrink-0 items-center gap-1.5 rounded px-2 py-1.5 transition-colors hover:bg-white/15"
                >
                  <SkipForward className="size-4" />
                  <span className="hidden text-[12px] font-medium sm:inline">Next</span>
                </button>
              )}
              <TimeDisplay current={currentTime} total={duration} />
            </>
          )}

          <div className="flex-1" />

          <VolumeControl
            volume={volume}
            muted={muted}
            onMute={() => handle.setMuted(!muted)}
            onVolume={(v) => handle.setVolume(v)}
          />

          {/* Subtitle picker — unified list (WebVTT + ASS + PGS). */}
          {manifest.subtitles.length > 0 && (
            <MenuButton
              label={`Subs${
                props.activeSubtitle ? ` · ${props.activeSubtitle.lang?.toUpperCase() ?? "ON"}` : ""
              }`}
              icon={<Captions className="size-4" />}
              open={menu === "subs"}
              onToggle={() => setMenu(menu === "subs" ? "none" : "subs")}
            >
              <SubtitleMenu
                subs={manifest.subtitles}
                active={props.activeSubtitle}
                onSelect={(t) => {
                  props.onSubtitleChange(t);
                  setMenu("none");
                }}
              />
            </MenuButton>
          )}

          {/* Audio picker — multi-language / multi-channel. */}
          {audioTracks.length > 1 && (
            <MenuButton
              label="Audio"
              icon={<Languages className="size-4" />}
              open={menu === "audio"}
              onToggle={() => setMenu(menu === "audio" ? "none" : "audio")}
            >
              <AudioMenu
                tracks={audioTracks}
                onSelect={(id) => {
                  props.onAudioPick(id);
                  setMenu("none");
                }}
              />
            </MenuButton>
          )}

          {props.documentPip.supported && (
            <Button
              label="Picture-in-picture"
              icon={<PictureInPicture2 className="size-4" />}
              onClick={() => void props.documentPip.toggle()}
              active={props.documentPip.isActive}
            />
          )}
          <Button
            label={debugOpen ? "Hide debug info" : "Debug info"}
            icon={<Bug className="size-4" />}
            active={debugOpen}
            onClick={() => setDebugOpen((v) => !v)}
          />
          <Button
            label="Fullscreen"
            icon={<Maximize className="size-4" />}
            onClick={() => void toggleFullscreen(props.fullscreenTarget)}
          />
        </div>
      </div>
    </div>
  );
}

function ScrubBar(props: {
  durationSeconds: number | null;
  currentSeconds: number;
  bufferedRanges: Array<[number, number]>;
  onScrub: (seconds: number) => void;
  onScrubEnd: (seconds: number) => void;
}) {
  const trackRef = useRef<HTMLDivElement>(null);
  const dragging = useRef(false);
  if (!props.durationSeconds || props.durationSeconds <= 0) {
    return (
      <div className="h-1.5 w-full rounded bg-white/15" aria-hidden>
        {/* No duration yet — show a flat track */}
      </div>
    );
  }
  const dur = props.durationSeconds;
  const pct = Math.min(100, Math.max(0, (props.currentSeconds / dur) * 100));

  const seekFromEvent = (e: PointerEvent | React.PointerEvent): number => {
    const track = trackRef.current;
    if (!track) return 0;
    const rect = track.getBoundingClientRect();
    const x = Math.max(0, Math.min(rect.width, e.clientX - rect.left));
    return (x / rect.width) * dur;
  };
  const onPointerDown = (e: React.PointerEvent<HTMLDivElement>) => {
    e.currentTarget.setPointerCapture(e.pointerId);
    dragging.current = true;
    props.onScrub(seekFromEvent(e));
  };
  const onPointerMove = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!dragging.current) return;
    props.onScrub(seekFromEvent(e));
  };
  const onPointerUp = (e: React.PointerEvent<HTMLDivElement>) => {
    if (!dragging.current) return;
    dragging.current = false;
    const target = seekFromEvent(e);
    props.onScrubEnd(target);
  };

  return (
    <div
      ref={trackRef}
      // `touch-none` stops the drag from also scrolling the page on a
      // phone; a slightly taller track on mobile is easier to grab.
      className="relative h-2.5 w-full cursor-pointer touch-none rounded bg-white/15 sm:h-2"
      tabIndex={0}
      aria-label="Seek"
      onPointerDown={onPointerDown}
      onPointerMove={onPointerMove}
      onPointerUp={onPointerUp}
      // <input type="range"> can't layer the buffered-range segments under
      // the thumb, so the scrub bar stays a div with explicit slider ARIA.
      // oxlint-disable-next-line jsx-a11y/prefer-tag-over-role
      role="slider"
      aria-valuemin={0}
      aria-valuemax={dur}
      aria-valuenow={props.currentSeconds}
    >
      {/* Buffered ranges */}
      {props.bufferedRanges.map(([s, e], i) => {
        const left = (s / dur) * 100;
        const width = ((e - s) / dur) * 100;
        return (
          <div
            key={i}
            className="absolute top-0 h-full bg-white/30"
            style={{ left: `${left}%`, width: `${width}%` }}
          />
        );
      })}
      {/* Playhead progress */}
      <div
        className="absolute left-0 top-0 h-full rounded bg-primary"
        style={{ width: `${pct}%` }}
      />
      {/* Knob */}
      <div
        className="absolute top-1/2 h-3.5 w-3.5 -translate-x-1/2 -translate-y-1/2 rounded-full bg-white shadow"
        style={{ left: `${pct}%` }}
      />
    </div>
  );
}

function TimeDisplay({ current, total }: { current: number; total: number | null }) {
  return (
    <span className="ml-0.5 shrink-0 select-none font-mono text-[11px] tabular-nums opacity-80 sm:ml-1 sm:text-[12px]">
      {formatTime(current)}
      {/* Total time is dropped on mobile to keep the control bar from
          overflowing a narrow player; shown from `sm` up. */}
      <span className="hidden sm:inline">
        {" / "}
        {total != null ? formatTime(total) : "--:--"}
      </span>
    </span>
  );
}

function VolumeControl(props: {
  volume: number;
  muted: boolean;
  onMute: () => void;
  onVolume: (v: number) => void;
}) {
  const display = props.muted ? 0 : props.volume;
  return (
    <div className="group flex items-center gap-1">
      <Button
        label={props.muted ? "Unmute" : "Mute"}
        icon={props.muted ? <VolumeX className="size-4" /> : <Volume2 className="size-4" />}
        onClick={props.onMute}
      />
      <input
        type="range"
        min={0}
        max={1}
        step={0.01}
        value={display}
        onChange={(e) => props.onVolume(Number(e.target.value))}
        className={
          // Track collapses to 0 width unless the wrapper is hovered.
          // The slider *thumb* gets explicit appearance rules so it
          // also hides — without them browsers paint the OS-default
          // dot OUTSIDE the 0-width track, which is what the user
          // was seeing as a stray dot.
          "h-1 w-0 cursor-pointer appearance-none rounded bg-white/30 transition-all group-hover:w-20" +
          " [&::-webkit-slider-thumb]:size-3 [&::-webkit-slider-thumb]:appearance-none" +
          " [&::-webkit-slider-thumb]:rounded-full [&::-webkit-slider-thumb]:bg-white" +
          " [&::-webkit-slider-thumb]:opacity-0 group-hover:[&::-webkit-slider-thumb]:opacity-100" +
          " [&::-moz-range-thumb]:size-3 [&::-moz-range-thumb]:appearance-none" +
          " [&::-moz-range-thumb]:rounded-full [&::-moz-range-thumb]:border-0 [&::-moz-range-thumb]:bg-white" +
          " [&::-moz-range-thumb]:opacity-0 group-hover:[&::-moz-range-thumb]:opacity-100"
        }
      />
    </div>
  );
}

function MenuButton(props: {
  label: string;
  icon: React.ReactNode;
  open: boolean;
  onToggle: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="relative">
      <Button label={props.label} icon={props.icon} onClick={props.onToggle} active={props.open} />
      {props.open && (
        <div className="absolute bottom-full right-0 mb-2 max-h-72 w-64 overflow-auto rounded bg-black/90 p-1 shadow-lg ring-1 ring-white/10">
          {props.children}
        </div>
      )}
    </div>
  );
}

function SubtitleMenu(props: {
  subs: SubtitleTrack[];
  active: SubtitleTrack | null;
  onSelect: (track: SubtitleTrack | null) => void;
}) {
  return (
    <ul className="divide-y divide-white/5">
      <li>
        <button
          onClick={() => props.onSelect(null)}
          className={`w-full px-2 py-1.5 text-left text-[12px] hover:bg-white/10 ${
            props.active == null ? "bg-white/10" : ""
          }`}
        >
          Off
        </button>
      </li>
      {props.subs.map((sub) => {
        const kind = subtitleOverlayKind(sub);
        const isActive = props.active?.stream_idx === sub.stream_idx;
        const label = sub.title ?? sub.lang?.toUpperCase() ?? `Sub ${sub.stream_idx}`;
        return (
          <li key={sub.stream_idx}>
            <button
              onClick={() => props.onSelect(sub)}
              className={`flex w-full items-center justify-between gap-2 px-2 py-1.5 text-left text-[12px] hover:bg-white/10 ${
                isActive ? "bg-white/10" : ""
              }`}
            >
              <span className="line-clamp-1">{label}</span>
              <span className="rounded bg-white/10 px-1 py-0.5 text-[9px] uppercase tracking-wide opacity-70">
                {kind === "native" ? sub.codec : kind}
              </span>
            </button>
          </li>
        );
      })}
    </ul>
  );
}

function AudioMenu(props: { tracks: EngineAudioTrack[]; onSelect: (id: string) => void }) {
  return (
    <ul className="divide-y divide-white/5">
      {props.tracks.map((t) => (
        <li key={t.id}>
          <button
            onClick={() => props.onSelect(t.id)}
            className={`flex w-full items-center justify-between gap-2 px-2 py-1.5 text-left text-[12px] hover:bg-white/10 ${
              t.active ? "bg-white/10" : ""
            }`}
          >
            <span className="line-clamp-1">{t.label}</span>
            {t.lang && (
              <span className="rounded bg-white/10 px-1 py-0.5 text-[9px] uppercase tracking-wide opacity-70">
                {t.lang}
              </span>
            )}
          </button>
        </li>
      ))}
    </ul>
  );
}

function Button(props: {
  label: string;
  icon: React.ReactNode;
  onClick: () => void;
  active?: boolean;
}) {
  return (
    <button
      title={props.label}
      aria-label={props.label}
      onClick={props.onClick}
      className={`grid size-8 shrink-0 place-items-center rounded transition-colors hover:bg-white/15 sm:size-9 ${
        props.active ? "bg-white/15" : ""
      }`}
    >
      {props.icon}
    </button>
  );
}

function formatTime(sec: number): string {
  if (!Number.isFinite(sec) || sec < 0) return "--:--";
  const total = Math.floor(sec);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

export async function toggleFullscreen(target: HTMLElement | null): Promise<void> {
  if (!target) return;
  if (document.fullscreenElement === target) {
    try {
      await document.exitFullscreen();
    } catch {
      /* ignore */
    }
  } else {
    try {
      await target.requestFullscreen();
    } catch {
      /* ignore */
    }
  }
}
