// web-svelte/src/lib/home/PreferencesEditor.svelte
<script lang="ts">
	// What a person likes, for the suggestions: the languages they would rather watch in (the
	// server's list, so a new language needs no client release), and genres, Anime among them
	// as its own category (not TMDB's Animation). Each choice a toggle button that says whether
	// it is on (`aria-pressed`, and a tick: never color alone). Stateless: the caller keeps the
	// choice and saves it.
	import type { GenreOption, LanguageOption } from '@iris/api/client';
	import Icon from '#lib/components/Icon.svelte';

	interface Props {
		languages: readonly string[];
		genres: readonly number[];
		includeAnime: boolean;
		languageOptions: readonly LanguageOption[];
		languagesLoading?: boolean;
		genreOptions: readonly GenreOption[];
		genresLoading?: boolean;
		onToggleLanguage: (value: string) => void;
		onToggleGenre: (id: number) => void;
		onToggleAnime: () => void;
	}
	let {
		languages,
		genres,
		includeAnime,
		languageOptions,
		languagesLoading = false,
		genreOptions,
		genresLoading = false,
		onToggleLanguage,
		onToggleGenre,
		onToggleAnime
	}: Props = $props();
	const id = $props.id();
</script>

<div class="prefs">
	<fieldset aria-describedby="{id}-lang-hint">
		<legend class="label">Languages</legend>
		<p class="hint" id="{id}-lang-hint">What you would rather watch in. Releases in these come first.</p>
		{#if languagesLoading}
			<p class="hint">Loading languages…</p>
		{:else}
			<div class="choices">
				{#each languageOptions as l (l.value)}
					{@render choice(l.label, languages.includes(l.value), () => onToggleLanguage(l.value))}
				{/each}
			</div>
		{/if}
	</fieldset>
	<fieldset aria-describedby="{id}-genre-hint">
		<legend class="label">Genres</legend>
		<p class="hint" id="{id}-genre-hint">
			Pick a few you enjoy. Anime is its own category, apart from Animation. Leave all off for a bit of everything.
		</p>
		<div class="choices">
			{@render choice('Anime', includeAnime, onToggleAnime)}
			{#if genresLoading}
				<span class="hint">Loading genres…</span>
			{:else}
				{#each genreOptions as g (g.id)}
					{@render choice(g.name, genres.includes(g.id), () => onToggleGenre(g.id))}
				{/each}
			{/if}
		</div>
	</fieldset>
</div>

{#snippet choice(label: string, on: boolean, toggle: () => void)}
	<button type="button" class="pill-btn" class:on aria-pressed={on} onclick={toggle}>
		{#if on}<Icon name="check" size={16} />{/if}{label}
	</button>
{/snippet}

<style>
	.prefs {
		display: grid;
		gap: var(--s-5);
	}
	fieldset {
		display: grid;
		gap: var(--s-2);
		margin: 0;
		padding: 0;
		border: 0;
		min-width: 0;
	}
	legend {
		padding: 0;
		margin-bottom: var(--s-1);
	}
	.choices {
		display: flex;
		flex-wrap: wrap;
		gap: var(--s-2);
	}
	.choices .pill-btn {
		min-height: var(--control-h-s);
	}
</style>

// web/src/components/PreferencesEditor.tsx
import { Check } from "lucide-react";

import type { GenreOption, LanguageOption } from "@iris/api/client";
import { cn } from "@/lib/utils";

type Props = {
  languages: string[];
  genres: number[];
  includeAnime: boolean;
  /** Server-driven selectable languages — never hardcoded client-side so
   *  adding a language is a backend-only change. */
  languageOptions: LanguageOption[];
  languagesLoading?: boolean;
  genreOptions: GenreOption[];
  genresLoading?: boolean;
  onToggleLanguage: (value: string) => void;
  onToggleGenre: (id: number) => void;
  onToggleAnime: () => void;
};

/**
 * Presentational editor for a user's recommendation preferences —
 * shared between the first-login OnboardingDialog and the Account page's
 * "Recommendations" card. Stateless: the parent owns the selection and
 * persistence. No timers / effects (CLAUDE.md web rule) — pure render.
 */
export function PreferencesEditor({
  languages,
  genres,
  includeAnime,
  languageOptions,
  languagesLoading,
  genreOptions,
  genresLoading,
  onToggleLanguage,
  onToggleGenre,
  onToggleAnime,
}: Props) {
  return (
    <div className="grid gap-6">
      <Section
        title="Languages"
        hint="What you'd rather watch in. We surface releases in these first."
      >
        {languagesLoading ? (
          <p className="text-[13px] text-muted-foreground">Loading languages…</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {languageOptions.map((l) => (
              <Chip
                key={l.value}
                selected={languages.includes(l.value)}
                onClick={() => onToggleLanguage(l.value)}
              >
                {l.label}
              </Chip>
            ))}
          </div>
        )}
      </Section>

      <Section
        title="Genres"
        hint="Pick a few you enjoy. Anime is its own category, distinct from Animation. Leave empty for a bit of everything."
      >
        <div className="flex flex-wrap gap-2">
          {/* Anime is a distinct category — NOT TMDB's "Animation" genre.
              It's backed by the AniList pipeline and driven by the separate
              include_anime preference, so it's always selectable here even
              before (or without) the TMDB genre list. */}
          <Chip selected={includeAnime} onClick={onToggleAnime} accent>
            Anime
          </Chip>
          {genresLoading ? (
            <span className="self-center text-[13px] text-muted-foreground">Loading genres…</span>
          ) : (
            genreOptions.map((g) => (
              <Chip key={g.id} selected={genres.includes(g.id)} onClick={() => onToggleGenre(g.id)}>
                {g.name}
              </Chip>
            ))
          )}
        </div>
      </Section>
    </div>
  );
}

function Section({
  title,
  hint,
  children,
}: {
  title: string;
  hint: string;
  children: React.ReactNode;
}) {
  return (
    <div className="grid gap-2.5">
      <div className="grid gap-0.5">
        <span className="text-sm font-medium text-foreground">{title}</span>
        <span className="text-[12.5px] text-fg-dim">{hint}</span>
      </div>
      {children}
    </div>
  );
}

function Chip({
  selected,
  onClick,
  accent,
  children,
}: {
  selected: boolean;
  onClick: () => void;
  /** Marks a special category (e.g. Anime) with a brand-tinted resting
   *  border so it reads as distinct from the plain TMDB genre chips. */
  accent?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      aria-pressed={selected}
      onClick={onClick}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[13px] font-medium transition",
        selected
          ? "border-primary bg-primary/15 text-foreground"
          : accent
            ? "border-primary/40 bg-elev text-foreground hover:border-primary"
            : "border-border bg-elev text-muted-foreground hover:text-foreground",
      )}
    >
      {selected && <Check className="size-3.5" />}
      {children}
    </button>
  );
}
