// web-svelte/src/lib/account/PreferencesEditor.svelte
<script lang="ts">
	// What « For You » is tuned by, picked by pressing (each choice a toggle button that says
	// whether it is on, a tick for the eye): languages most wanted, genres enjoyed, and Anime,
	// its own category (not TMDB's Animation). The choices come from the server. Stateless:
	// Account's Recommendations and the first-run onboarding own the picks and their saving.
	import type { GenreOption, LanguageOption } from '@iris/api/client';
	import Icon from '#lib/components/Icon.svelte';
	import { toggled, type Picks } from './preferences.ts';

	interface Props {
		picks: Picks;
		onchange: (next: Picks) => void;
		languages: readonly LanguageOption[] | undefined;
		genres: readonly GenreOption[] | undefined;
	}
	let { picks, onchange, languages, genres }: Props = $props();
	const id = $props.id();
</script>

{#snippet pill(on: boolean, label: string, press: () => void)}
	<button type="button" class="pill-btn" class:on aria-pressed={on} onclick={press}>
		{#if on}<Icon name="check" size={14} />{/if}{label}
	</button>
{/snippet}

<div class="editor">
	<div class="choice" role="group" aria-labelledby="{id}-lang" aria-describedby="{id}-lang-hint">
		<p class="label" id="{id}-lang">Languages</p>
		<p class="hint" id="{id}-lang-hint">What you would rather watch in. Releases in these come first.</p>
		<div class="pills">
			{#if languages}
				{#each languages as l (l.value)}
					{@render pill(picks.languages.includes(l.value), l.label, () =>
						onchange({ ...picks, languages: toggled(picks.languages, l.value) })
					)}
				{/each}
			{:else}
				<p class="hint">Loading the languages…</p>
			{/if}
		</div>
	</div>
	<div class="choice" role="group" aria-labelledby="{id}-genres" aria-describedby="{id}-genres-hint">
		<p class="label" id="{id}-genres">Genres</p>
		<p class="hint" id="{id}-genres-hint">
			Pick a few you enjoy, or none for a bit of everything. Anime is its own category, apart from Animation.
		</p>
		<div class="pills">
			{@render pill(picks.include_anime, 'Anime', () => onchange({ ...picks, include_anime: !picks.include_anime }))}
			{#if genres}
				{#each genres as gen (gen.id)}
					{@render pill(picks.genres.includes(gen.id), gen.name, () => onchange({ ...picks, genres: toggled(picks.genres, gen.id) }))}
				{/each}
			{:else}
				<p class="hint">Loading the genres…</p>
			{/if}
		</div>
	</div>
</div>

<style>
	.editor {
		display: grid;
		gap: var(--s-5);
	}
	.choice {
		display: grid;
		gap: var(--s-2);
	}
	.choice p {
		margin: 0;
	}
	.pills {
		display: flex;
		flex-wrap: wrap;
		gap: var(--s-2);
	}
</style>

// web/src/components/PreferencesEditor.tsx
import { Check } from "lucide-react";

import type { GenreOption, LanguageOption } from "@iris/api/client";
import { cn } from "@/lib/utils";

type Props = {
  languages: string[];
  genres: number[];
  includeAnime: boolean;
  /** Server-driven selectable languages — never hardcoded client-side so
   *  adding a language is a backend-only change. */
  languageOptions: LanguageOption[];
  languagesLoading?: boolean;
  genreOptions: GenreOption[];
  genresLoading?: boolean;
  onToggleLanguage: (value: string) => void;
  onToggleGenre: (id: number) => void;
  onToggleAnime: () => void;
};

/**
 * Presentational editor for a user's recommendation preferences —
 * shared between the first-login OnboardingDialog and the Account page's
 * "Recommendations" card. Stateless: the parent owns the selection and
 * persistence. No timers / effects (CLAUDE.md web rule) — pure render.
 */
export function PreferencesEditor({
  languages,
  genres,
  includeAnime,
  languageOptions,
  languagesLoading,
  genreOptions,
  genresLoading,
  onToggleLanguage,
  onToggleGenre,
  onToggleAnime,
}: Props) {
  return (
    <div className="grid gap-6">
      <Section
        title="Languages"
        hint="What you'd rather watch in. We surface releases in these first."
      >
        {languagesLoading ? (
          <p className="text-[13px] text-muted-foreground">Loading languages…</p>
        ) : (
          <div className="flex flex-wrap gap-2">
            {languageOptions.map((l) => (
              <Chip
                key={l.value}
                selected={languages.includes(l.value)}
                onClick={() => onToggleLanguage(l.value)}
              >
                {l.label}
              </Chip>
            ))}
          </div>
        )}
      </Section>

      <Section
        title="Genres"
        hint="Pick a few you enjoy. Anime is its own category, distinct from Animation. Leave empty for a bit of everything."
      >
        <div className="flex flex-wrap gap-2">
          {/* Anime is a distinct category — NOT TMDB's "Animation" genre.
              It's backed by the AniList pipeline and driven by the separate
              include_anime preference, so it's always selectable here even
              before (or without) the TMDB genre list. */}
          <Chip selected={includeAnime} onClick={onToggleAnime} accent>
            Anime
          </Chip>
          {genresLoading ? (
            <span className="self-center text-[13px] text-muted-foreground">Loading genres…</span>
          ) : (
            genreOptions.map((g) => (
              <Chip key={g.id} selected={genres.includes(g.id)} onClick={() => onToggleGenre(g.id)}>
                {g.name}
              </Chip>
            ))
          )}
        </div>
      </Section>
    </div>
  );
}

function Section({
  title,
  hint,
  children,
}: {
  title: string;
  hint: string;
  children: React.ReactNode;
}) {
  return (
    <div className="grid gap-2.5">
      <div className="grid gap-0.5">
        <span className="text-sm font-medium text-foreground">{title}</span>
        <span className="text-[12.5px] text-fg-dim">{hint}</span>
      </div>
      {children}
    </div>
  );
}

function Chip({
  selected,
  onClick,
  accent,
  children,
}: {
  selected: boolean;
  onClick: () => void;
  /** Marks a special category (e.g. Anime) with a brand-tinted resting
   *  border so it reads as distinct from the plain TMDB genre chips. */
  accent?: boolean;
  children: React.ReactNode;
}) {
  return (
    <button
      type="button"
      aria-pressed={selected}
      onClick={onClick}
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-[13px] font-medium transition",
        selected
          ? "border-primary bg-primary/15 text-foreground"
          : accent
            ? "border-primary/40 bg-elev text-foreground hover:border-primary"
            : "border-border bg-elev text-muted-foreground hover:text-foreground",
      )}
    >
      {selected && <Check className="size-3.5" />}
      {children}
    </button>
  );
}
